Updates to `report` CLI. Closes #1390
turbot/steampipe pull request #1393
Opened 2022-02-03 18:16 UTC by binaek

2022-02-04 14:35 UTC, kaidaguerre requested changes

2022-02-04 14:35 UTC, kaidaguerre commented on report/reportserver/server.go
> +	log.Println("[ERROR] buildLeafNodeProgressPayload marshal error:", err)
do we really want to print that out?

2022-02-07 06:47 UTC, binaek commented on report/reportserver/api.go
> +
done

2022-02-07 06:47 UTC, binaek commented on report/reportserver/server.go
> +	log.Println("[ERROR] buildLeafNodeProgressPayload marshal error:", err)
removed

2022-02-08 10:13 UTC, kaidaguerre requested changes

2022-02-08 10:13 UTC, kaidaguerre commented on report/reportserver/server.go
> +// we don't expect the build functions to ever error during marshalling
move this comment to the calling code where the panic is

2022-02-08 10:13 UTC, kaidaguerre commented on report/reportserver/server.go
> +		if err != nil {
can we put the panic into a defer block so we only call it once

2022-02-08 10:13 UTC, kaidaguerre commented on report/reportserver/server.go
> +		if err != nil {
i.e. set an `err` variable and break instead of panicking - then check `err` in the defer

2022-02-08 12:12 UTC, merged