Add support for finding `mod.sp` up `cwd` tree. Closes #1533
turbot/steampipe pull request #1536
Opened 2022-03-01 15:56 UTC by binaek

2022-03-02 09:48 UTC, kaidaguerre requested changes

2022-03-02 09:48 UTC, kaidaguerre commented on tests/acceptance/test_files/022.mod-sp-traversal.bats
> +# Running steampipe check from folder1 should return an error, since the mod.sp file is present nowhere
```Running steampipe check from folder1 (i.e. _above_ the mod folder) should return an error, ...```

2022-03-02 09:48 UTC, kaidaguerre commented on workspace/workspace_error.go
> +	ErrModSpNotFound = errors.New("this command requires a mod definition file - could not find in the current directory tree")
ErrorNoModDefinition

2022-03-02 09:55 UTC, pskrbasu commented on tests/acceptance/test_files/022.mod-sp-traversal.bats
> +# Running steampipe check from folder1 should return an error, since the mod.sp file is present nowhere
updated comment

2022-03-04 17:26 UTC, kaidaguerre requested changes

2022-03-04 17:26 UTC, kaidaguerre commented on cmd/dashboard.go
> +				state, _ := dashboardserver.GetDashboardServiceState()
wrap in a function

2022-03-04 17:26 UTC, kaidaguerre commented on cmd/dashboard.go
> +		state := &dashboardserver.DashboardServiceState{
wrap in a function

2022-03-04 17:26 UTC, kaidaguerre commented on constants/exit_codes.go
> +	EC_NoModFile = 15
So tell me - what am I going to say about this variable name?

Now try to ask yourself that question before submitting the PR :p 

`ExitCodeNoModFile` please

And if we are defining consts for exit codes (a good idea), please raise an issue to use them consistently for all commands

2022-03-04 17:26 UTC, kaidaguerre commented on dashboard/dashboardserver/service.go
>  	pingTimer := time.NewTicker(10 * time.Millisecond)
10 ms seems a bit too fast - 25? 50?

2022-03-04 17:26 UTC, kaidaguerre commented on dashboard/dashboardserver/service.go
> +	timeoutAt := time.After(5 * time.Second)
const for timeout please

2022-03-04 17:26 UTC, kaidaguerre commented on dashboard/dashboardserver/service.go
> +	stateBytes, err := json.Marshal(state)
lets use MarshalIndent

2022-03-07 14:41 UTC, kaidaguerre requested changes

2022-03-07 14:41 UTC, kaidaguerre commented on dashboard/dashboardserver/service.go
> +			if len(state.Error) > 0 {
update comment - `// check the state file for an error`

2022-03-07 14:41 UTC, kaidaguerre commented on dashboard/dashboardserver/service.go
> +			// we loaded the state and there was no error -- aal-is-well
delete `-- aal-is-well`

2022-03-07 14:41 UTC, kaidaguerre commented on workspace/workspace.go
> +	return len(w.modFileLocation) > 0
lets call this `modFilePath` for consistency

2022-03-07 14:41 UTC, kaidaguerre commented on cmd/dashboard.go
> +				state, _ := dashboardserver.GetDashboardServiceState()
```
if isRunningAsService() {
    saveErrorToDashboardState()
}
```

2022-03-07 14:41 UTC, kaidaguerre commented on cmd/dashboard.go
> +		state := &dashboardserver.DashboardServiceState{
```
if isRunningAsService() {
    saveDashboardState()
}
```

2022-03-07 15:04 UTC, binaek commented on workspace/workspace.go
>  	modFile, err := w.findModFilePath(w.Path)
we do now!

https://github.com/turbot/steampipe/pull/1536/commits/897963707b701e608f6edea43445ec24cdc28700

2022-03-07 15:52 UTC, merged