Launch failure when using Root. Closes #167
turbot/steampipe pull request #214
Opened 2021-02-22 16:46 UTC by binaek89

2021-02-23 09:54 UTC, binaek89 commented
![Screenshot 2021-02-22 at 10 34 45 PM](https://user-images.githubusercontent.com/1114038/108827079-2563e480-75eb-11eb-8ea9-02054b833d6a.png)

@e-gineer @johnsmyth  this is what we are showing when `steampipe` is run as a super-user.

2021-02-23 10:18 UTC, kaidaguerre requested changes

2021-02-23 10:18 UTC, kaidaguerre commented on main.go
> +// static void
can we delete this?

2021-02-23 10:18 UTC, kaidaguerre commented on main.go
> +	if os.Geteuid() != os.Getuid() {
if this is needed, can you get this error signed off by John/Nathan as well

2021-02-23 16:03 UTC, johnsmyth approved these changes

2021-02-23 19:13 UTC, binaek89 commented
@johnsmyth @e-gineer @kaidaguerre 

there's another error string which is shown when the `real` userID is not equal to the `effective` userID:

`steampipe: real and effective user IDs must match`

The idea is to replicate the behaviour as is laid out in `postgresql`, so that we can avoid the scenario where `steampipe` starts up, but the underlying `postgresql` refuses to startup.

2021-02-23 19:58 UTC, e-gineer commented
Steampipe should not be in bold for the "root" error message above?

Please share exact output for the real / effective error for review.

2021-02-24 08:41 UTC, binaek89 commented
> Steampipe should not be in bold for the "root" error message above?

👍  I will remove the **bold**

> 
> Please share exact output for the real / effective error for review.

The exact output from `postgres` is 
`postgres: real and effective user IDs must match`

Ours is pretty much an exact copy (except the bold part)

2021-02-24 08:46 UTC, binaek89 commented
@e-gineer 

update:

I removed the `steampipe:` from the error, since we don't use it anywhere else.

Attaching a screenshot of the actual output

![Screenshot 2021-02-24 at 2 14 46 PM](https://user-images.githubusercontent.com/1114038/108973876-e39a7300-76aa-11eb-9b26-fc71f162e80d.png)

2021-02-24 13:49 UTC, merged