Fixes issue where prompt fails to show up when service installation runs in interactive mode
turbot/steampipe pull request #2548
Opened 2022-10-18 11:21 UTC by binaek

2022-10-19 09:40 UTC, binaek commented
https://user-images.githubusercontent.com/1114038/196655866-da9ba5ae-118f-4119-afc9-e40cfd0e1ef1.mov

2022-10-20 09:26 UTC, kaidaguerre requested changes

2022-10-20 09:26 UTC, kaidaguerre commented on pkg/interactive/interactive_client_init.go
> +	initResult.AddWarnings("this is a hard coded watning")
please remove test code

2022-10-20 09:28 UTC, binaek commented on pkg/interactive/interactive_client_init.go
> +	initResult.AddWarnings("this is a hard coded watning")
Oops!

2022-10-21 11:13 UTC, merged