Fix issue where connection setup prematurely times out
turbot/steampipe pull request #2981
Opened 2023-01-11 13:56 UTC by binaek

2023-01-11 17:01 UTC, kaidaguerre requested changes

2023-01-11 17:37 UTC, binaek commented on pkg/db/db_common/wait_connection.go
> +		err := retry.RetryableError(connection.Ping(timeoutCtx))
ah - that got left behind

2023-01-11 17:40 UTC, binaek commented on pkg/db/db_local/create_client.go
> +	err = retry.Do(ctx, backoff, func(rCtx context.Context) error {
doen

2023-01-11 17:40 UTC, binaek commented on pkg/db/db_local/create_client.go
> +	backoff = retry.WithMaxRetries(
done

2023-01-11 17:40 UTC, binaek commented on pkg/db/db_local/create_client.go
> +	err = db_common.WaitForConnection(ctx, conn)
👍

2023-01-11 17:41 UTC, binaek commented on pkg/db/db_common/wait_connection.go
> +	return retry.Do(ctx, retry.WithMaxDuration(
👍

2023-01-11 17:41 UTC, binaek commented on pkg/db/db_common/wait_connection.go
👍

2023-01-12 21:49 UTC, vhadianto commented on pkg/db/db_common/wait_connection.go
> +			if pgErr, ok := pingErr.(*pgconn.PgError); ok && pgErr.SQLState() == "57P03" {
I haven't checked this but we should also wait if Postgres is doing auto recovery.

In a large database this can take "a long time".

2023-01-18 14:19 UTC, kaidaguerre requested changes

2023-01-18 14:26 UTC, merged