add flag for deleting default plugin config
turbot/steampipe pull request #3660
Opened 2023-07-07 11:01 UTC by Mr-Destructive

Addressing #3531 

- Have added a `--default-config` flag on `plugin install` command, it is set to `true` by default.
- To omit the setting of default config for the installed plugin the user needs to set it to false.

```
steampipe plugin install --default-config=false supabase
```

The approach is to join the path of the default config dir i.e. `~/.steampipe/config/` and the plugin name with the `.spc` extension. Is there a better way to obtain the file path of the plugin config?
Let me know if this approach is valid, or is it a bit hacky?

Thank you.

2023-07-07 15:06 UTC, binaek commented
Hi @Mr-Destructive 

Thank you for the contribution. It looks like we are still to finalise on how to approach the problem that @cbruno10 raised. 

We will pick this up at the earliest.

While we 'zero' down on it, can you add the tests to verify that the functionality works. This will ensure that changes in the area don't end up breaking the feature.

The test file should be `service_and_plugin.bats`.

2023-07-07 15:31 UTC, Mr-Destructive commented
Sure, will add those👍

2023-07-21 10:55 UTC, pskrbasu requested changes
@Mr-Destructive requested some changes. Please take a look.

Here's a small gist of how to achieve this:

- The func [installPlugin](https://github.com/turbot/steampipe/blob/854819f8f141267348ea1b9f6aaec28e1b959a50/cmd/plugin.go#L529) should accept WithSkipConfig() as an input, which would be passed down the stack till here in [InstallPlugin](https://github.com/turbot/steampipe/blob/854819f8f141267348ea1b9f6aaec28e1b959a50/pkg/ociinstaller/plugin.go#L53).
- We would then validate whether WithSkipConfig is true or false using an if block in [L53](https://github.com/turbot/steampipe/blob/854819f8f141267348ea1b9f6aaec28e1b959a50/pkg/ociinstaller/plugin.go#L53)
- Based on that the config file will either be written or not written.

Take a look at https://github.com/turbot/steampipe/pull/3338/files. This has a similar structure. We want to design it exactly like this.

Let us know if you need any help with this.

2023-07-21 10:55 UTC, pskrbasu commented on cmd/plugin.go
> +	if !defaultConfig {
This is not the right way to solve this issue.

Consider this scenario:
1. steampipe plugin install aws - (aws.spc file gets created)
2. configure aws.spc with creds and query
3. steampipe plugin uninstall aws - (plugin gets uninstalled, but aws.spc stays on)
4. steampipe plugin install aws ----default-config=false - (would delete the existing aws.spc config)

We should not remove the config but rather prevent its creation in the first place.

2023-07-21 10:55 UTC, pskrbasu commented on pkg/constants/args.go
> +	ArgDefaultConfig           = "default-config"
rename it to `skip-config`
```suggestion
	ArgSkipConfig           = "skip-config"
```

2023-07-22 10:51 UTC, Mr-Destructive commented
Are the changes fine? It will require changing the signature of the InstallPlugins in the `ociinstaller/plugin`.  

Other changes I need to confirm:
- Moving the `configFileOption` to a separate file?
- Can't the `--skip-config` be directly checked at `ociiinstaller/plugin` level function to call from `viper.GetBool(constants.ArgsSkipConfig)` (is this a bad practice or it won't work?)

Let me know if I am going wrong here. Thank you

2023-07-24 08:38 UTC, pskrbasu commented on cmd/plugin.go
> +type configFileOption struct {
```suggestion
type pluginInstallConfig struct {
```

2023-07-24 09:07 UTC, pskrbasu requested changes
@Mr-Destructive please take a look at the changes requested and get back if you need help.

To answer your questions:
> - Moving the configFileOption to a separate file?

Yes, move it to a separate file in ociinstaller package. It should not stay in cmd. (Move L50-67 in cmd/plugin.go to ociinstaller package)

> - Can't the --skip-config be directly checked at ociiinstaller/plugin level function to call from viper.GetBool(constants.ArgsSkipConfig) (is this a bad practice or it won't work?)

The simplest answer is it can 😁. But we don't want to do it that way. Our code goes through 3levels of packages here - the top level being `cmd`, then it goes into `plugin` and finally into `ociinstaller`. The `--skip-config` is passed at the topmost level. So checking it in the 3rd level would mean there's no existence of it in the levels between(which is not clean code). Hence we want to pass it down as options in every single level to make the code better.

> Also, should I add the test cases for this scenario?

Yes that is a valid scenario and it would be great if you can add a test to replicate that. Thanks

2023-07-24 09:07 UTC, pskrbasu commented on cmd/plugin.go
> +type configFileOption struct {
```suggestion
type pluginInstallConfig struct {
```
Move these into ociinstaller package

2023-07-24 09:07 UTC, pskrbasu commented on cmd/plugin.go
> +	skip bool
```suggestion
	skipConfigFile bool
```

2023-07-24 09:08 UTC, pskrbasu commented on cmd/plugin.go
> +type SkipConfigFile = func(config *configFileOption)
Move these into ociinstaller

2023-07-24 11:09 UTC, Mr-Destructive commented
Thank you for the detailed help. Have made the changes and added the test.

Is the test valid?  Let me know of any further changes.
Thank you

2023-07-26 08:33 UTC, pskrbasu requested changes
@Mr-Destructive Thank you for making the changes. The tests look good.

A few minor changes are requested. Thanks!

2023-07-26 08:33 UTC, pskrbasu commented on pkg/ociinstaller/plugin.go
> +	skipPluginConfig := config.skipConfigFile
These lines should be the first lines of the func. (Not a biggie nor it is wrong, it's just how we have done it elsewhere 😄 )

Having another variable here seems excessive. You don't need another variable here `skipPluginConfig` (just use `config.skipConfigFile` wherever needed)

2023-07-26 08:33 UTC, pskrbasu commented on tests/acceptance/test_files/service_and_plugin.bats
> +  run steampipe plugin install aws --skip-config=false --install-dir $tmpdir
--skip-config by default is false. No need to add the flag here.

2023-07-27 12:05 UTC, pskrbasu requested changes
@Mr-Destructive The changes look good.
Just one minor change is requested. Please take a look and rebase with the latest main(has conflicts). 

Thanks!

2023-07-27 12:05 UTC, pskrbasu commented on pkg/ociinstaller/config.go
> +func WithSkipConfigEnabled(skipConfigFile bool) PluginInstallOption {
```suggestion
func WithSkipConfig(skipConfigFile bool) PluginInstallOption {
```

2023-07-27 12:16 UTC, binaek commented
@Mr-Destructive could you also rebase your branch

2023-07-28 09:15 UTC, merged