Update BuildFullResourceName to validate for non empty arguments. Closes #3601
turbot/steampipe pull request #3718
Opened 2023-08-03 09:44 UTC by pskrbasu

2023-08-04 08:42 UTC, binaek requested changes

2023-08-04 08:42 UTC, binaek commented on pkg/dashboard/dashboardexecute/dashboard_execution_tree.go
> +
line not required

2023-08-04 08:42 UTC, binaek commented on pkg/steampipeconfig/modconfig/dashboard.go
remove blank line

2023-08-04 08:42 UTC, binaek commented on pkg/steampipeconfig/modconfig/parsed_name.go
> +	if err != nil {
error check not required - just do
`return BuildFullResourceName...`

2023-08-04 08:42 UTC, binaek commented on pkg/steampipeconfig/modconfig/parsed_name.go
> +		if err != nil {
error check not required - see above

2023-08-04 08:42 UTC, binaek commented on pkg/steampipeconfig/modconfig/parsed_name.go
> +	if err != nil {
error check not required

2023-08-07 10:35 UTC, kaidaguerre requested changes

2023-08-07 10:35 UTC, kaidaguerre commented on pkg/dashboard/dashboardexecute/snapshot.go
> +		snapshot.FileNameRoot, err = parsedName.ToFullNameWithMod(w.Mod.ShortName)
```
// set the filename root of the snapshot
		fileRootName, err := parsedName.ToFullNameWithMod(w.Mod.ShortName)
		if err != nil{
			return nil, err
		}
		snapshot.FileNameRoot = fileRootName
		
```

2023-08-07 12:37 UTC, kaidaguerre approved these changes

2023-08-07 12:39 UTC, merged