Fix quoting issue while schema cloning. Closes #3753
turbot/steampipe pull request #3754
Opened 2023-08-17 14:00 UTC by pskrbasu

2023-08-18 09:04 UTC, binaek commented
We need tests . . .

2023-08-18 13:05 UTC, binaek requested changes

2023-08-18 13:05 UTC, binaek commented on tests/acceptance/test_files/schema_cloning.bats
> +@test "schema cloning - quoting issue" {
Rename this test to `Verify mixed case connection name works`

2023-08-25 09:31 UTC, kaidaguerre approved these changes

2023-08-25 09:32 UTC, merged